apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "external-ingress"
  namespace: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: external-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "backend-service"
              servicePort: 80
